# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json
AWSTemplateFormatVersion: '2010-09-09'
Description: Backend static  (APIGW + Lambda + DynamoDB) for put recipe

Parameters:
  SystemId:
    Type: String
    Default: 'kondate-5036514'
    Description: SystemId
  Env:
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'prod'
    Description: Environment
  StageName:
    Type: String
    Default: dev
    Description: API stage name
  TableName:
    Type: String
    Default: MenuLooperTable
    Description: DynamoDB table name
  FunctionName:
    Type: String
    Default: MenuLooperCreateRecipe
    Description: Lambda function name
  PermissionsBoundaryArn:
    Type: String
    Default: arn:aws:iam::978150176570:policy/PermissionsBoundaryPolicy
    Description: Permissions boundary to satisfy IAM create role restrictions

Resources:
  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Ref PermissionsBoundaryArn
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoPutItem
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt RecipeTable.Arn
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId


  CreateRecipeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Code:
        ZipFile: |
          import base64
          import json
          import os
          import uuid
          from datetime import datetime, timezone
          from decimal import Decimal

          import boto3

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table(os.environ["TABLE_NAME"])

          def _response(status, body):
              return {
                  "statusCode": status,
                  "headers": {
                      "Content-Type": "application/json",
                      "Access-Control-Allow-Origin": "*",
                  },
                  "body": json.dumps(body),
              }

          def handler(event, context):
              body_str = event.get("body") or ""
              if event.get("isBase64Encoded"):
                  try:
                      body_str = base64.b64decode(body_str).decode("utf-8")
                  except Exception:
                      return _response(400, {"message": "invalid json"})

              try:
                  payload = json.loads(body_str, parse_float=Decimal)
                  if not isinstance(payload, dict):
                      raise ValueError("payload is not object")
              except Exception:
                  return _response(400, {"message": "invalid json"})

              user_id = payload.get("userId") or "anonymous"
              recipe_id = str(uuid.uuid4())
              now = (
                  datetime.now(timezone.utc)
                  .replace(microsecond=0)
                  .isoformat()
                  .replace("+00:00", "Z")
              )

              item = {
                  "pk": f"USER#{user_id}",
                  "sk": f"RECIPE#{recipe_id}",
                  "entityType": "RECIPE",
                  "recipeId": recipe_id,
                  "createdAt": now,
                  "updatedAt": now,
                  "raw": payload,
              }

              for key in [
                  "recipeName",
                  "url",
                  "baseServings",
                  "tags",
                  "ingredients",
                  "stepsMemo",
              ]:
                  if key in payload and payload[key] is not None:
                      item[key] = payload[key]

              try:
                  table.put_item(Item=item)
              except Exception:
                  return _response(500, {"message": "internal error"})

              return _response(201, {"recipeId": recipe_id})
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId

  CreateRecipeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: 14
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId


  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${FunctionName}-api"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - content-type
          - x-amz-date
          - authorization
          - x-api-key
          - x-amz-security-token
        MaxAge: 86400
      Tags:
        Owner: yukanagatake
        SystemId: !Ref SystemId
        Env: !Ref Env

  CreateRecipeIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateRecipeFunction.Arn}/invocations"
      PayloadFormatVersion: '2.0'

  CreateRecipeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /recipes"
      Target: !Sub "integrations/${CreateRecipeIntegration}"

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref StageName
      AutoDeploy: true
      Tags:
        Owner: yukanagatake
        SystemId: !Ref SystemId
        Env: !Ref Env

  ApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateRecipeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/POST/recipes"

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  DynamoTableName:
    Value: !Ref TableName
