# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json
AWSTemplateFormatVersion: '2010-09-09'
Description: Backend stack (API Gateway + Lambda + DynamoDB)

Parameters:
  SystemId:
    Type: String
    Default: 'kondate-loop'
    Description: SystemId
  Env:
    Type: String
    Default: 'prod'
    AllowedValues:
      - 'dev'
      - 'prod'
    Description: Environment
  LambdaCodeS3Key:
    Type: String
    Default: ''
    Description: S3 key for Lambda zip. If empty, inline placeholder is used.
  LambdaCodeS3Bucket:
    Type: String
    Default: ''
    Description: Optional S3 bucket for Lambda zip. If empty, imported backend code bucket is used.
  LambdaCodeS3ObjectVersion:
    Type: String
    Default: ''
    Description: Optional S3 object version for Lambda zip.
  LambdaHandler:
    Type: String
    Default: index.handler
    Description: Lambda handler (e.g. index.handler)
  LambdaRuntime:
    Type: String
    Default: nodejs18.x
    Description: Lambda runtime
  ApiDeploymentVersion:
    Type: String
    Default: ''
    Description: Bump this value to force API Gateway deployment refresh.
  EnableGSI1:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable DynamoDB GSI1
  EnableGSI2:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable DynamoDB GSI2
  EnableGSI3:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable DynamoDB GSI3

Conditions:
  UseS3Code: !Not [!Equals [!Ref LambdaCodeS3Key, '']]
  UseS3BucketOverride: !Not [!Equals [!Ref LambdaCodeS3Bucket, '']]
  HasCodeVersion: !Not [!Equals [!Ref LambdaCodeS3ObjectVersion, '']]
  EnableGSI1Condition: !Equals [!Ref EnableGSI1, 'true']
  EnableGSI2Condition: !Equals [!Ref EnableGSI2, 'true']
  EnableGSI3Condition: !Equals [!Ref EnableGSI3, 'true']

Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${SystemId}-${Env}-data-ddb-main'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - !If
          - EnableGSI1Condition
          - AttributeName: GSI1PK
            AttributeType: S
          - !Ref AWS::NoValue
        - !If
          - EnableGSI1Condition
          - AttributeName: GSI1SK
            AttributeType: S
          - !Ref AWS::NoValue
        - !If
          - EnableGSI2Condition
          - AttributeName: GSI2PK
            AttributeType: S
          - !Ref AWS::NoValue
        - !If
          - EnableGSI2Condition
          - AttributeName: GSI2SK
            AttributeType: S
          - !Ref AWS::NoValue
        - !If
          - EnableGSI3Condition
          - AttributeName: GSI3PK
            AttributeType: S
          - !Ref AWS::NoValue
        - !If
          - EnableGSI3Condition
          - AttributeName: GSI3SK
            AttributeType: S
          - !Ref AWS::NoValue
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - !If
          - EnableGSI1Condition
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - !Ref AWS::NoValue
        - !If
          - EnableGSI2Condition
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2PK
                KeyType: HASH
              - AttributeName: GSI2SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - !Ref AWS::NoValue
        - !If
          - EnableGSI3Condition
          - IndexName: GSI3
            KeySchema:
              - AttributeName: GSI3PK
                KeyType: HASH
              - AttributeName: GSI3SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - !Ref AWS::NoValue
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Owner
          Value: yukanagatake

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${SystemId}-${Env}-user-pool'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        Owner: yukanagatake

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${SystemId}-${Env}-web-client'
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 1
      IdTokenValidity: 1
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: hours
        IdToken: hours
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  BackendFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SystemId}-${Env}-api-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt MainTable.Arn
                  - !Sub '${MainTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - cognito-idp:SignUp
                  - cognito-idp:AdminConfirmSignUp
                  - cognito-idp:InitiateAuth
                  - cognito-idp:GetUser
                  - cognito-idp:GlobalSignOut
                  - cognito-idp:RevokeToken
                Resource: '*'

  BackendFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${SystemId}-${Env}-api-fn-proxy'
      Runtime: !Ref LambdaRuntime
      Handler: !Ref LambdaHandler
      Role: !GetAtt BackendFunctionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MainTable
          DATA_STORE_DRIVER: dynamo
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
          COGNITO_REGION: !Ref AWS::Region
      Code:
        Fn::If:
          - UseS3Code
          - S3Bucket:
              !If
                - UseS3BucketOverride
                - !Ref LambdaCodeS3Bucket
                - Fn::ImportValue: !Sub '${SystemId}-${Env}-backend-code-bucket-name'
            S3Key: !Ref LambdaCodeS3Key
            S3ObjectVersion: !If
              - HasCodeVersion
              - !Ref LambdaCodeS3ObjectVersion
              - !Ref AWS::NoValue
          - ZipFile: |
              exports.handler = async () => {
                return {
                  statusCode: 200,
                  body: JSON.stringify({ message: "placeholder" }),
                };
              };
      Tags:
        - Key: Owner
          Value: yukanagatake

  BackendApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${SystemId}-${Env}-api'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Owner
          Value: yukanagatake

  RootProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BackendApi
      ParentId: !GetAtt BackendApi.RootResourceId
      PathPart: '{proxy+}'

  RootProxyAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BackendApi
      ResourceId: !Ref RootProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  V1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BackendApi
      ParentId: !GetAtt BackendApi.RootResourceId
      PathPart: v1

  V1AnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BackendApi
      ResourceId: !Ref V1Resource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BackendApi
      ParentId: !Ref V1Resource
      PathPart: '{proxy+}'

  ProxyAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BackendApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200

  BackendApiDeploymentV2:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RootProxyAnyMethod
      - V1AnyMethod
      - ProxyAnyMethod
    Properties:
      RestApiId: !Ref BackendApi
      StageName: !Ref Env
      Description: !Sub 'deployment-${ApiDeploymentVersion}'

  BackendFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BackendFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendApi}/*/*/v1/*'

  BackendFunctionPermissionV1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BackendFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendApi}/*/*/v1'

  BackendFunctionPermissionRootProxy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BackendFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendApi}/*/*/*'

Outputs:
  BackendApiEndpoint:
    Description: API endpoint base URL
    Value: !Sub 'https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/v1'
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
  MainTableName:
    Description: DynamoDB main table
    Value: !Ref MainTable
  BackendFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt BackendFunction.Arn
