# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal infra static  (CloudFront + S3)

Parameters:
  CorsAllowOrigin:
    Type: String
    Default: '*'
    Description: Allowed origin for API CORS. Use a specific domain for production.
  Env:
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'prod'
    Description: Environment
  StaticBucketName:
    Type: String
    Default: ''
    Description: Optional existing S3 bucket name for static assets. If set, the stack will not create a new bucket.

Conditions:
  CreateStaticBucket: !Equals [!Ref StaticBucketName, '']

Resources:
  StaticBucket:
    Condition: CreateStaticBucket
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'kondate-loop-${Env}-s3-web-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Owner
          Value: yukanagatake

  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !If [CreateStaticBucket, !Ref StaticBucket, !Ref StaticBucketName]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !If
              - CreateStaticBucket
              - !Sub '${StaticBucket.Arn}/*'
              - !Sub 'arn:aws:s3:::${StaticBucketName}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'


  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: StaticS3
            DomainName: !If
              - CreateStaticBucket
              - !GetAtt StaticBucket.RegionalDomainName
              - !Sub '${StaticBucketName}.s3.${AWS::Region}.amazonaws.com'
            OriginAccessControlId: !Ref StaticOriginAccessControl
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: StaticS3
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: !Ref StaticCachePolicy
      Tags:
        - Key: Owner
          Value: yukanagatake

  StaticCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${AWS::StackName}-cf-cachepolicy-static'
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true

  StaticOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-cf-oac-static'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
