# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json
AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions OIDC bootstrap (IAM roles + OIDC provider)

Parameters:
  SystemId:
    Type: String
    Default: 'kondate-loop'
    Description: SystemId
  GitHubOrg:
    Type: String
    Default: kondate-team
    Description: GitHub organization name
  GitHubRepo:
    Type: String
    Default: kondate-loop
    Description: GitHub repository name
  DevFrontendBucketName:
    Type: String
    Default: kondate-loop-dev-s3-web-211669976488-ap-northeast-1
    Description: S3 bucket for dev frontend assets
  ProdFrontendBucketName:
    Type: String
    Default: kondate-loop-prod-s3-web-211669976488-ap-northeast-1
    Description: S3 bucket for prod frontend assets
  ArtifactsBucketName:
    Type: String
    Default: kondate-loop-infra-s3-artifacts-211669976488-ap-northeast-1
    Description: S3 bucket for build artifacts
  DevBackendCodeBucketName:
    Type: String
    Default: kondate-loop-dev-backend-s3-lambda-code-211669976488-ap-northeast-1
    Description: S3 bucket for dev backend Lambda code packages
  ProdBackendCodeBucketName:
    Type: String
    Default: kondate-loop-prod-backend-s3-lambda-code-211669976488-ap-northeast-1
    Description: S3 bucket for prod backend Lambda code packages
  DevStackName:
    Type: String
    Default: kondate-loop-backend-stack
    Description: CloudFormation stack name for dev
  ProdStackName:
    Type: String
    Default: PRODkondate-loop-backend-stack
    Description: CloudFormation stack name for prod
  CfnExecutionRoleDevManagedPolicyArn:
    Type: String
    Default: arn:aws:iam::aws:policy/AdministratorAccess
    Description: >
      Managed policy ARN for dev execution role. Use least privilege once verified.
  CfnExecutionRoleProdManagedPolicyArn:
    Type: String
    Default: arn:aws:iam::aws:policy/AdministratorAccess
    Description: >
      Managed policy ARN for prod execution role. Do NOT keep AdministratorAccess in production.

Resources:
  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      # CloudFormation requires ThumbprintList. Replace with the real thumbprint in production.
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId

  CfnExecutionRoleDev:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SystemId}-dev-cfn-exec'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CfnExecutionRoleDevManagedPolicyArn
      Policies:
        - PolicyName: CfnCloudFrontManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:ListCachePolicies
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  - cloudfront:ListTagsForResource
                Resource: '*'
        - PolicyName: CfnS3BucketManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                Resource:
                  - !Sub 'arn:aws:s3:::kondate-loop-*-s3-web-*'
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Env
          Value: dev

  CfnExecutionRoleProd:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SystemId}-prod-cfn-exec'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CfnExecutionRoleProdManagedPolicyArn
      Policies:
        - PolicyName: CfnCloudFrontManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:ListCachePolicies
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  - cloudfront:ListTagsForResource
                Resource: '*'
        - PolicyName: CfnS3BucketManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                Resource:
                  - !Sub 'arn:aws:s3:::kondate-loop-*-s3-web-*'
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Env
          Value: prod

  GitHubDeployRoleDev:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SystemId}-dev-github-deploy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              # NOTE: GitHub Actions jobs must run on refs/heads/dev to match this sub.
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/dev'
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              # NOTE: GitHub Actions jobs must run on refs/heads/feature/* to match this sub.
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/feature/*'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DevFrontendBucketName}'
                  - !Sub 'arn:aws:s3:::${ProdFrontendBucketName}'
                  - !Sub 'arn:aws:s3:::${ArtifactsBucketName}'
                  - !Sub 'arn:aws:s3:::${DevBackendCodeBucketName}'
                  - !Sub 'arn:aws:s3:::${ProdBackendCodeBucketName}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DevFrontendBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ProdFrontendBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ArtifactsBucketName}/*'
                  - !Sub 'arn:aws:s3:::${DevBackendCodeBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ProdBackendCodeBucketName}/*'
        - PolicyName: CloudFormationDeploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:ListChangeSets
                  - cloudformation:ValidateTemplate
                Resource: '*'
        - PolicyName: CloudFrontManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:ListCachePolicies
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  - cloudfront:ListTagsForResource
                Resource: '*'
        - PolicyName: S3BucketManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                Resource:
                  - !Sub 'arn:aws:s3:::kondate-loop-*-s3-web-*'
        - PolicyName: PassCfnExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                Resource:
                  - !GetAtt CfnExecutionRoleDev.Arn
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Env
          Value: dev

  GitHubDeployRoleProd:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SystemId}-prod-github-deploy'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              # NOTE: GitHub Actions jobs must run on refs/heads/main to match this sub.
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DevFrontendBucketName}'
                  - !Sub 'arn:aws:s3:::${ProdFrontendBucketName}'
                  - !Sub 'arn:aws:s3:::${ArtifactsBucketName}'
                  - !Sub 'arn:aws:s3:::${DevBackendCodeBucketName}'
                  - !Sub 'arn:aws:s3:::${ProdBackendCodeBucketName}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DevFrontendBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ProdFrontendBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ArtifactsBucketName}/*'
                  - !Sub 'arn:aws:s3:::${DevBackendCodeBucketName}/*'
                  - !Sub 'arn:aws:s3:::${ProdBackendCodeBucketName}/*'
        - PolicyName: CloudFormationDeploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:ListChangeSets
                  - cloudformation:ValidateTemplate
                Resource: '*'
        - PolicyName: CloudFrontManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:ListCachePolicies
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  - cloudfront:ListTagsForResource
                Resource: '*'
        - PolicyName: S3BucketManage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                Resource:
                  - !Sub 'arn:aws:s3:::kondate-loop-*-s3-web-*'
        - PolicyName: PassCfnExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                Resource:
                  - !GetAtt CfnExecutionRoleProd.Arn
      Tags:
        - Key: Owner
          Value: yukanagatake
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Env
          Value: prod

Outputs:
  GitHubDeployRoleDevArn:
    Description: GitHub Actions OIDC role ARN (dev)
    Value: !GetAtt GitHubDeployRoleDev.Arn
  GitHubDeployRoleProdArn:
    Description: GitHub Actions OIDC role ARN (prod)
    Value: !GetAtt GitHubDeployRoleProd.Arn
  CfnExecutionRoleDevArn:
    Description: CloudFormation execution role ARN (dev)
    Value: !GetAtt CfnExecutionRoleDev.Arn
  CfnExecutionRoleProdArn:
    Description: CloudFormation execution role ARN (prod)
    Value: !GetAtt CfnExecutionRoleProd.Arn
  OidcProviderArn:
    Description: GitHub OIDC provider ARN
    Value: !Ref GitHubOidcProvider
